[tool.poetry]
name = "helloworld"
version = "0.1.0"
description = ""
authors = ["Robert Martin <robert.d.martin@icloud.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
